const REST = 'organizations';
const REST_USER = 'users';

export const ORGANIZATION_PATH = {
    ADD_NEW_USER_TO_ORGANIZATION: `v1/${REST}/{id}/${REST_USER}/{userId}`,
    ADD_USER_FOR_DEFAULT_LANGUAGE_CODE_ORGANIZATION_SYSTEM: `v1/${REST}/${REST_USER}/{userId}`,
    ASSIGN_ROLE_FOR_USER_IN_ORGANIZATION: `v1/${REST}/{id}/assign-role-users`,

    CREATE_ORGANIZATION: `v1/${REST}`,
    DELETE_ORGANIZATION: `v1/${REST}/{id}`,
    GET_ORGANIZATION: `v1/${REST}/{id}`,
    GET_ORGANIZATIONS: `v1/${REST}`,

    GET_USERS_OF_ORGANIZATION: `v1/${REST}/{id}/${REST_USER}`,
    REMOVE_USERS_IN_ORGANIZATION: `v1/${REST}/{id}/${REST_USER}/{userId}`,
    UPDATE_ORGANIZATION: `v1/${REST}/{id}`,
    UPDATE_USER_STATUS_IN_ORGANIZATION: `v1/${REST}/{id}/${REST_USER}`,
};
