import { REST_BRAND } from '../paths';

const REST_BRAND_EMAIL_ADDRESS = 'emails';

/**
 * #JFW-361
 */
export const BRAND_EMAIL_ADDRESS_PATH = {
    GET_EMAILS_WITH_BRAND: `v1/${REST_BRAND}/:id/${REST_BRAND_EMAIL_ADDRESS}`,
    UPDATE_BRAND_EMAIL_ADDRESS: `v1/${REST_BRAND}/:id/${REST_BRAND_EMAIL_ADDRESS}`,
};
