import { REST_BRAND } from '../paths';

const REST_BRAND_EMAIL_ADDRESS = 'emails';

export const BRAND_EMAIL_ADDRESS_PATH = {
    GET_EMAILS_WITH_BRAND: `${REST_BRAND}/:id/${REST_BRAND_EMAIL_ADDRESS}`,
    UPDATE_BRAND_EMAIL_ADDRESS: `${REST_BRAND}/:id/${REST_BRAND_EMAIL_ADDRESS}`,
};
