import { REST_INTEGRATION } from '../paths';

const REST_APP_INTEGRATION_SMTP = `${REST_INTEGRATION}/smtp`;

export const APP_INTEGRATION_SMTP_PATH = {
    CREATE_APP_INTEGRATION_SMTP: `v1/${REST_APP_INTEGRATION_SMTP}`,
    DELETE_APP_INTEGRATION_SMTP: `v1/${REST_APP_INTEGRATION_SMTP}/:id`,
    GET_APP_INTEGRATION_SMTP: `v1/${REST_APP_INTEGRATION_SMTP}/:id`,
    GET_APPS_INTEGRATION_SMTP_WITH_BRAND: `v1/${REST_APP_INTEGRATION_SMTP}`,
    TEST_SENDING_EMAIL_ADDRESS_MESSAGE: `v1/${REST_APP_INTEGRATION_SMTP}/test`,
    UPDATE_APP_INTEGRATION_SMTP: `v1/${REST_APP_INTEGRATION_SMTP}/:id`,
};
