import { REST_INTEGRATION } from '../paths';

const REST_APP_INTEGRATION_SMTP = `${REST_INTEGRATION}/smtp`;

export const APP_INTEGRATION_SMTP_PATH = {
    CREATE_APP_INTEGRATION_SMTP: `${REST_APP_INTEGRATION_SMTP}`,
    DELETE_APP_INTEGRATION_SMTP: `${REST_APP_INTEGRATION_SMTP}/:id`,
    GET_APP_INTEGRATION_SMTP: `${REST_APP_INTEGRATION_SMTP}/:id`,
    GET_APP_INTEGRATION_SMTPS_WITH_BRAND: `${REST_APP_INTEGRATION_SMTP}`,
    SEND_TEST_EMAIL: `${REST_APP_INTEGRATION_SMTP}/test`,
    UPDATE_APP_INTEGRATION_SMTP: `${REST_APP_INTEGRATION_SMTP}/:id`,
};
