import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_SMTP = `${REST_INTEGRATION}/smtp`;

export const INTEGRATION_SMTP_PATH = {
    QUERY: `${REST_INTEGRATION_SMTP}`,
    CREATE: `${REST_INTEGRATION_SMTP}`,
    UPDATE_BY_ID: `${REST_INTEGRATION_SMTP}/:id`,
    GET_BY_ID: `${REST_INTEGRATION_SMTP}/:id`,
    DELETE_BY_ID: `${REST_INTEGRATION_SMTP}/:id`,
};
