import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_AUTHENTICATION = `${REST_INTEGRATION}/authentication`;

export const APP_INTEGRATION_AUTHENTICATION_PATH = {
    CREATE_APP_INTEGRATION_AUTHENTICATION: `v1/${REST_INTEGRATION_AUTHENTICATION}`,
    DELETE_APP_INTEGRATION_AUTHENTICATION: `v1/${REST_INTEGRATION_AUTHENTICATION}/:id`,
    GET_APP_INTEGRATION_AUTHENTICATION: `v1/${REST_INTEGRATION_AUTHENTICATION}/:id`,
    GET_APPS_INTEGRATION_AUTHENTICATION_WITH_BRAND: `v1/${REST_INTEGRATION_AUTHENTICATION}`,
    TEST_BUILDING_AUTHENTICATION_URL: `v1/${REST_INTEGRATION}/:appIntegrationId/authentication/test`,
    UPDATE_APP_INTEGRATION_AUTHENTICATION: `v1/${REST_INTEGRATION_AUTHENTICATION}/:id`,
};
