import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_AUTHENTICATION = `${REST_INTEGRATION}/authentication`;

export const INTEGRATION_AUTHENTICATION_PATH = {
    QUERY: `${REST_INTEGRATION_AUTHENTICATION}`,
    CREATE: `${REST_INTEGRATION_AUTHENTICATION}`,
    UPDATE_BY_ID: `${REST_INTEGRATION_AUTHENTICATION}/:id`,
    GET_BY_ID: `${REST_INTEGRATION_AUTHENTICATION}/:id`,
    DELETE_BY_ID: `${REST_INTEGRATION_AUTHENTICATION}/:id`,
};
