export enum WalletHistoryType {
    Unknown = 'Unknown',
    LicensePurchase = 'LicensePurchase',
    Payment = 'Payment',
    Refund = 'Refund',
    Void = 'Void',
    Capture = 'Capture',
    Authorization = 'Authorization',
    Reversal = 'Reversal',
    Inquiry = 'Inquiry',
    WalletAddMoney = 'WalletAddMoney',
    WalletWithdraw = 'WalletWithdraw',
    WalletEarningCoin = 'WalletEarningCoin',
    WalletRedeem = 'WalletRedeem',
    WalletConvert = 'WalletConvert',
}

export enum WalletHistoryStatus {
    Waiting = 'Waiting',
    Completed = 'Completed',
    Refunded = 'Refunded',
    Failed = 'Failed',
    Pending = 'Pending',
    Denied = 'Denied',
    Reserved = 'Reserved',
    CanceledReversal = 'CanceledReversal',
    Deleted = 'Deleted',
    Voided = 'Voided',
    Expired = 'Expired',
}
