import { REST_INTEGRATION } from '../paths';

const REST_APP_INTEGRATION_SMS = `${REST_INTEGRATION}/sms`;

export const APP_INTEGRATION_SMS_PATH = {
    CREATE_APP_INTEGRATION_SMS: `v1/${REST_APP_INTEGRATION_SMS}`,
    DELETE_APP_INTEGRATION_SMS: `v1/${REST_APP_INTEGRATION_SMS}/{id}`,
    GET_APP_INTEGRATION_SMS: `v1/${REST_APP_INTEGRATION_SMS}/{id}`,
    GET_APPS_INTEGRATION_SMS_WITH_BRAND: `v1/${REST_APP_INTEGRATION_SMS}`,
    TEST_SENDING_SMS_MESSAGE: `v1/${REST_INTEGRATION}/{appIntegrationId}/sms/test`,
    UPDATE_APP_INTEGRATION_SMS: `v1/${REST_APP_INTEGRATION_SMS}/{id}`,
};
