import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_ANALYTICS = `${REST_INTEGRATION}/analytics`;

export const APP_INTEGRATION_ANALYTICS_PATH = {
    CREATE_APP_INTEGRATION_ANALYTICS: `v1/${REST_INTEGRATION_ANALYTICS}`,
    DELETE_APP_INTEGRATION_ANALYTICS: `v1/${REST_INTEGRATION_ANALYTICS}/{id}`,
    GET_APP_INTEGRATION_ANALYTICS: `v1/${REST_INTEGRATION_ANALYTICS}/{id}`,
    GET_APP_INTEGRATION_ANALYTICS_WITH_BRAND: `v1/${REST_INTEGRATION_ANALYTICS}`,
    UPDATE_APP_INTEGRATION_ANALYTICS: `v1/${REST_INTEGRATION_ANALYTICS}/{id}`,
};
