import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_PUSH_NOTIFICATION = `${REST_INTEGRATION}/push-notification`;

export const INTEGRATION_PUSH_NOTIFICATION_PATH = {
    GET: `${REST_INTEGRATION_PUSH_NOTIFICATION}`,
    CREATE: `${REST_INTEGRATION_PUSH_NOTIFICATION}`,
    UPDATE_BY_ID: `${REST_INTEGRATION_PUSH_NOTIFICATION}/:id`,
    GET_BY_ID: `${REST_INTEGRATION_PUSH_NOTIFICATION}/:id`,
    DELETE_BY_ID: `${REST_INTEGRATION_PUSH_NOTIFICATION}/:id`,
};
