import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_PUSH_NOTIFICATION = `${REST_INTEGRATION}/push-notification`;

export const APP_INTEGRATION_PUSH_NOTIFICATION_PATH = {
    CREATE_APP_INTEGRATION_PUSH_NOTIFICATION: `v1/${REST_INTEGRATION_PUSH_NOTIFICATION}`,
    CREATE_APP_INTEGRATION_PUSH_NOTIFICATION_WITH_IMPORT_FILE_SETTINGS: `v1/${REST_INTEGRATION_PUSH_NOTIFICATION}/import`,
    DELETE_APP_INTEGRATION_PUSH_NOTIFICATION: `v1/${REST_INTEGRATION_PUSH_NOTIFICATION}/{id}`,
    GET_APP_INTEGRATION_PUSH_NOTIFICATION: `v1/${REST_INTEGRATION_PUSH_NOTIFICATION}/{id}`,
    GET_APP_INTEGRATION_PUSH_NOTIFICATIONS_WITH_BRAND: `v1/${REST_INTEGRATION_PUSH_NOTIFICATION}`,
    UPDATE_APP_INTEGRATION_PUSH_NOTIFICATION: `v1/${REST_INTEGRATION_PUSH_NOTIFICATION}/{id}`,
};
