import { REST_INTEGRATION } from '../paths';

const REST_APP_INTEGRATION_RECAPTCHA = `${REST_INTEGRATION}/recaptcha`;

export const APP_INTEGRATION_RECAPTCHA_PATH = {
    CREATE_APP_INTEGRATION_RECAPTCHA: `v1/${REST_APP_INTEGRATION_RECAPTCHA}`,
    DELETE_APP_INTEGRATION_RECAPTCHA: `v1/${REST_APP_INTEGRATION_RECAPTCHA}/{id}`,
    GET_APP_INTEGRATION_RECAPTCHA: `v1/${REST_APP_INTEGRATION_RECAPTCHA}/{id}`,
    GET_APPS_INTEGRATION_RECAPTCHA_WITH_BRAND: `v1/${REST_APP_INTEGRATION_RECAPTCHA}`,
    TEST_SENDING_RECAPTCHA_MESSAGE: `v1/${REST_INTEGRATION}/{appIntegrationId}/sms/test`,
    UPDATE_APP_INTEGRATION_RECAPTCHA: `v1/${REST_APP_INTEGRATION_RECAPTCHA}/{id}`,
};
