const REST = 'subscription-types';

export const SUBSCRIPTION_TYPE_PATH = {
    CREATE_SUBSCRIPTION_TYPE: `${REST}`,
    DELETE_SUBSCRIPTION_TYPE: `${REST}/:id`,
    GET_SUBSCRIPTION_TYPES: `${REST}`,
    GET_SUBSCRIPTION_TYPE: `${REST}/:id`,
    UPDATE_SUBSCRIPTION_TYPE: `${REST}/:id`,
};
