import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_PAYMENT_GATEWAY = `${REST_INTEGRATION}/payment-gateway`;

export const APP_INTEGRATION_PAYMENT_GATEWAY_PATH = {
    CREATE_APP_INTEGRATION_PAYMENT_GATEWAY: `v1/${REST_INTEGRATION_PAYMENT_GATEWAY}`,
    DELETE_APP_INTEGRATION_PAYMENT_GATEWAY: `v1/${REST_INTEGRATION_PAYMENT_GATEWAY}/{id}`,
    GET_APP_INTEGRATION_PAYMENT_GATEWAY: `v1/${REST_INTEGRATION_PAYMENT_GATEWAY}/{id}`,
    GET_APPS_INTEGRATION_PAYMENT_GATEWAY_WITH_BRAND: `v1/${REST_INTEGRATION_PAYMENT_GATEWAY}`,
    TEST_CREATING_CHECKOUT_LINK: `v1/${REST_INTEGRATION}/{appIntegrationId}/payment-gateway/test`,
    UPDATE_APP_INTEGRATION_PAYMENT_GATEWAY: `v1/${REST_INTEGRATION_PAYMENT_GATEWAY}/{id}`,
};
