import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_PAYMENT_GATEWAY = `${REST_INTEGRATION}/payment-gateway`;

export const APP_INTEGRATION_PAYMENT_GATEWAY_PATH = {
    CREATE_APP_INTEGRATION_PAYMENT_GATEWAY: `${REST_INTEGRATION_PAYMENT_GATEWAY}`,
    DELETE_APP_INTEGRATION_PAYMENT_GATEWAY: `${REST_INTEGRATION_PAYMENT_GATEWAY}/:id`,
    GET_APP_INTEGRATION_PAYMENT_GATEWAY: `${REST_INTEGRATION_PAYMENT_GATEWAY}/:id`,
    GET_APP_INTEGRATION_PAYMENT_GATEWAYS_WITH_BRAND: `${REST_INTEGRATION_PAYMENT_GATEWAY}`,
    TESTING_FOR_CREATE_CHECKOUT_LINK: `${REST_INTEGRATION}/:appIntegrationId/payment-gateway/test`,
    UPDATE_APP_INTEGRATION_PAYMENT_GATEWAY: `${REST_INTEGRATION_PAYMENT_GATEWAY}/:id`,
};
