import { REST_INTEGRATION } from '../paths';

const REST_INTEGRATION_PAYMENT_GATEWAY = `${REST_INTEGRATION}/payment-gateway`;

export const INTEGRATION_PAYMENT_GATEWAY_PATH = {
    QUERY: `${REST_INTEGRATION_PAYMENT_GATEWAY}`,
    CREATE: `${REST_INTEGRATION_PAYMENT_GATEWAY}`,
    UPDATE_BY_ID: `${REST_INTEGRATION_PAYMENT_GATEWAY}/:id`,
    GET_BY_ID: `${REST_INTEGRATION_PAYMENT_GATEWAY}/:id`,
    DELETE_BY_ID: `${REST_INTEGRATION_PAYMENT_GATEWAY}/:id`,
};
